package com.example.AzureTestProject.Api.Model.Constant;

public enum AccountType {
    CASH,
    BANK,
    INVENTORY,
    ACCOUNTS_RECEIVABLE,
    SUPPLIES,
    PREPAID_EXPENSE,
    TOOLS,

    LAND,
    EQUIPMENT,
    BUILDING,
    VEHICLE,
    MACHINERY,

    ACCOUNT_PAYABLE,
    SHORT_TERM_LOANS,
    UNEARNED_REVENUE,
    ACCRUES_EXPENSE,

    LONG_TERM_LOANS,
    NOTES_PAYABLE,

    OWNER_DRAW,
    OWNER_CONTRIBUTION,
    OWNER_EQUITY,

    COMMON_STOCKS,
    RETAINED_EARNINGS,


    OTHER_SALES,
    REVENUE,
    SALES,

    DIRECT_MATERIALS_COST,
    DIRECT_LABOR_COST,
    SUB_CONTRACTING,
    MANUFACTURING_OVERHEAD,

    GENERAL_EXPENSES,
    SALARIES_AND_WAGES,
    UTILITIES,
    RENT,
    TELEPHONE,
    INTERNET,
    INSURRANCE,
    MAINTENANCE_AND_REPAIRS_EXPENSES,


    INTEREST_EXPENSES,
    DEPRECIATION,
    INCOME_TAX_EXPENSE,
    DIVIDENDS,
    TAXES,

    VAT_COLLECTED,
    VAT_PAID,
    VAT_PAYABLE,


    OTHER,

}
