package com.example.AzureTestProject.Api.Model.Constant;

public enum Priority {
    PLANNED_PRODUCTION_REQUIREMENT,
    SITE_EXECUTION_PROJECT_WORK_REQUIREMENT,
    SAMPLE_PROTOTYPE_MATERIAL_NEEDED,
    LOW_STOCK_REPLENISHMENT,
    NEW_SITE_OR_PROJECT_MOBILIZATION,
    CLIENT_DELIVERY_COMMITMENT,
    TOOLS_OR_CONSUMABLE_REPLACEMENT,
    MATERIAL_EXPIRY_OR_DAMAGE_REPLACEMENT,
    INTERNAL_TRANSFER_TO_ANOTHER_DEPARTMENT_SITE,
    TRIAL_RUN_OR_NEW_PRODUCT_TESTING,
    R_AND_D_OR_ENGINEERING_REQUIREMENT,
    URGENT_REQUIREMENT_NOT_IN_SCHEDULE,
    SUBCONTRACTOR_SUPPORT_REQUIREMENT,
    ASSET_EQUIPMENT_COMMISSIONING,
    INVENTORY_ADJUSTMENT_PHYSICAL_STOCK_CORRECTION
}
